import { app, BrowserWindow, dialog, ipcMain, shell } from 'electron';
import { autoUpdater, UpdateDownloadedEvent } from 'electron-updater';
import { isRastercueJobActive } from './rastercue-history';
import logit from './utils/logit';

/** The packaged provider is generated by electron-builder from YazeKT/Rastercue. */
export function registerRastercueUpdates(win: BrowserWindow) {
  autoUpdater.autoInstallOnAppQuit = false;
  autoUpdater.autoDownload = true;
  let pending: UpdateDownloadedEvent | null = null;
  let promptOpen = false;
  let snoozedUntil = 0;
  const check = async () => {
    snoozedUntil = 0;
    if (!app.isPackaged) return { ok: false, message: 'Update checks are available in installed Rastercue builds after its GitHub release is published.' };
    try { await autoUpdater.checkForUpdates(); return { ok: true, message: 'Checked Rastercue releases. Any available update downloads automatically.' }; }
    catch (error) { logit('Rastercue update check unavailable:', String(error)); return { ok: false, message: 'Could not check Rastercue releases. Check your connection or try again after the first release is published.' }; }
  };
  autoUpdater.on('error', error => logit('Rastercue updater:', String(error)));
  autoUpdater.on('update-downloaded', event => { pending = event; });
  const timer = setInterval(async () => {
    if (!pending || Date.now() < snoozedUntil || promptOpen || isRastercueJobActive() || win.isDestroyed()) return;
    promptOpen = true;
    try {
      const event = pending;
      const { response } = await dialog.showMessageBox(win, { type: 'info', title: 'Rastercue update ready', message: `Rastercue ${event.version} is ready to install.`, detail: 'Restart only when you are ready. Your local history and preferences are kept.', buttons: ['Restart and install', 'Later', 'Release notes'], defaultId: 1, cancelId: 1 });
      if (response === 0 && !isRastercueJobActive()) { pending = null; autoUpdater.quitAndInstall(); }
      else if (response === 2) { snoozedUntil = Date.now() + 3600000; await shell.openExternal(`https://github.com/YazeKT/Rastercue/releases/tag/v${encodeURIComponent(event.version)}`); }
      else snoozedUntil = Date.now() + 3600000;
    } finally { promptOpen = false; }
  }, 2000);
  timer.unref();
  win.on('closed', () => clearInterval(timer));
  win.webContents.on('did-finish-load', async () => {
    try {
      const enabled = await win.webContents.executeJavaScript('localStorage.getItem("autoUpdate") !== "false"');
      if (enabled) await check();
    } catch (error) { logit('Rastercue updater preference unavailable:', String(error)); }
  });
  ipcMain.handle('rastercue-updates:check', event => {
    if (event.sender !== win.webContents || event.senderFrame !== win.webContents.mainFrame) throw new Error('Untrusted update request.');
    return check();
  });
}
