import { useState } from 'react';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '../ui/dialog';
import RastercueLogo from '../icons/rastercue-logo';

export default function AboutDialog() {
  const [open,setOpen]=useState(false);
  const [tab,setTab]=useState('About');
  const [licence,setLicence]=useState('');
  const [status,setStatus]=useState('');
  const showLicence=async(filename:string)=>{try{const response=await fetch(filename);if(!response.ok)throw new Error('unavailable');setLicence(await response.text());}catch{setLicence('Licence text could not be loaded. The complete notices are also included with the source distribution.');}};
  return <><button className="btn btn-sm w-full" onClick={()=>setOpen(true)}>About, licences & changelog</button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="w-[90vw] max-w-3xl max-h-[90vh] overflow-y-auto">
    <DialogHeader><DialogTitle className="flex items-center gap-3"><RastercueLogo className="w-9 h-9 text-primary"/>Rastercue 1.0.0</DialogTitle><DialogDescription>Designer-focused image upscaling, based on Upscayl 2.15.0.</DialogDescription></DialogHeader>
    <div className="tabs tabs-boxed">{['About','Licences','Changelog'].map(label=><button key={label} className={`tab ${tab===label?'tab-active':''}`} onClick={()=>setTab(label)}>{label}</button>)}</div>
    {tab==='About'&&<div className="space-y-4 text-sm"><p>Rastercue’s identity, compact interface, inspection tools, model guidance and local job history are fork modifications by YazeKT. The underlying upscaling application is Upscayl, created by Nayam Amarshe and TGS963 with its contributors.</p><p>Engine: Upscayl-NCNN / Real-ESRGAN-ncnn-vulkan and their contributors, including Xintao Wang. Models retain their individual creator credits and licences.</p><p>No telemetry, cloud promotions or automatic image uploads. Local thumbnails and history can contain sensitive image previews and paths; protect the history folder as you would your design files.</p><p><a className="link" href="https://github.com/upscayl/upscayl" target="_blank" rel="noreferrer">Upstream source</a> · <a className="link" href="https://github.com/YazeKT/Rastercue" target="_blank" rel="noreferrer">Rastercue source and releases</a></p><button className="btn btn-sm" onClick={async()=>{setStatus('Checking…');try{const api=(window as unknown as {rastercueUpdates:{check:()=>Promise<{message:string}>}}).rastercueUpdates;setStatus((await api.check()).message);}catch{setStatus('Update checks are unavailable. Try an installed release.');}}}>Check for updates</button><p role="status">{status}</p></div>}
    {tab==='Licences'&&<div className="space-y-3 text-sm"><p>App source: AGPL-3.0. Rebranding does not remove upstream copyright or source-availability obligations. Engine and model licences are separate. Commercial-use notices in the model browser must be checked for your intended work.</p><div className="flex flex-wrap gap-2"><button className="btn btn-sm" onClick={()=>showLicence('LICENSE.txt')}>App licence</button><button className="btn btn-sm" onClick={()=>showLicence('Real-ESRGAN_LICENSE.txt')}>Real-ESRGAN notice</button><button className="btn btn-sm" onClick={()=>showLicence('Poppins-OFL.txt')}>Poppins font licence</button></div><pre className="max-h-[42vh] overflow-auto whitespace-pre-wrap select-text rounded bg-base-300 p-3 text-xs">{licence||'Choose a notice to read its complete text.'}</pre><p>Creator links and weight-identity limitations are recorded separately for every recognised model. Downloadable models do not automatically grant redistribution or commercial rights.</p></div>}
    {tab==='Changelog'&&<div className="space-y-3 text-sm"><h3 className="font-semibold">1.0.0 · Local release candidate</h3><ul className="list-disc pl-5 space-y-2"><li>Rastercue identity and dark-first compact permanent sidebars.</li><li>Expanded model guidance, favourites and named settings presets.</li><li>Aligned before/after manual zoom, pan and inspection bookmarks.</li><li>Local job records, sizes, thumbnails and safe output renaming.</li><li>Expanded searchable severity-labelled logs.</li><li>Removed telemetry/cloud promotion; fork-owned update destination.</li></ul><h3 className="font-semibold">Inherited from Upscayl 2.15.0</h3><p>Single, batch and double upscaling; NCNN/Vulkan engine; built-in/custom model loading; format, compression, tile, TTA, GPU, width and metadata options. Processing algorithms and model weights were not authored by this fork.</p><p>Cross-platform runtime and hosted-update verification are release gates, not claims made by this changelog.</p></div>}
  </DialogContent></Dialog></>;
}
